#+title: Simple REPL App
#+author: Gleefre
#+email: varedif.a.s@gmail.com

#+language: en
#+options: toc:nil

It is a simple app that starts [[https://github.com/Gleefre/simple-repl][Simple REPL]] on click.
~and-jni~, ~cl-android~ and ~android-log~ are preloaded,
as well as ~alexandria~, ~serapeum~, ~cffi~, ~usocket~ and ~bordeaux-threads~.

A prebuilt apk is available.
To build the app yourself just call ~./build-scripts/make-all.sh~.
* Connect to the running app instance
  App launches Simple REPL server on port ~4017~ on ~localhost~ interface.

  After connecting to the device with ~adb~ you need to setup port forwarding:
  #+BEGIN_SRC bash
  adb forward tcp:4017 tcp:4017
  #+END_SRC

  And then you can simply connect from any lisp on your computer:
  #+BEGIN_SRC lisp
  (ql:quickload :simple-repl/client)
  (simple-repl/server:run 4017)
  #+END_SRC
* Bugs & Contributions
  Feel free to report bugs or make suggestions by filing an issue on github.

  Feel free to submit pull requests on github as well.
* License
  Copyright 2023 Gleefre

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
